# THIS DOCKERFILE IS INTENDED FOR DEVELOPMENT ENVIRONMENTS
# DO NOT USE THIS FOR PRODUCTION USAGES.

version: "3"

services:
  api_server:
    build:
      dockerfile: Dockerfile
      context: .
    env_file: .env
    depends_on:
      - postgresDb
      - redis
    command: npm run start
    ports:
      - 8080:${PORT}

  postgresDb:
    image: docker.io/bitnami/postgresql:16
    ports:
      - "5432:5438"
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_DATABASE=mobarter_db
      - POSTGRESQL_USERNAME=mobarter_user
      - POSTGRESQL_PASSWORD=mobarter_pass

  redis:
    image: "redis:alpine"
    ports:
      - 6379:${REDIS_PORT}

volumes:
  postgresql_data:
    driver: local

