[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/server/Dockerfile"

[deploy]
runtime = "V2"
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/v1/health"
healthcheckTimeout = 50
sleepApplication = false
multiRegionConfig = { asia-southeast1-eqsg3a = { numReplicas = 1 } }
