export const GH = [
    {
        id: 153,
        operatorId: 153,
        name: 'Airtel-Tigo Ghana',
        bundle: false,
        data: false,
        pin: false,
        comboProduct: false,
        supportsLocalAmounts: true,
        supportsGeographicalRechargePlans: false,
        denominationType: 'RANGE',
        senderCurrencyCode: 'NGN',
        senderCurrencySymbol: '₦',
        destinationCurrencyCode: 'GHS',
        destinationCurrencySymbol: 'GH₵',
        commission: 5.0,
        internationalDiscount: 5.0,
        localDiscount: 0.0,
        mostPopularAmount: 25500,
        mostPopularLocalAmount: null,
        minAmount: 136.0,
        maxAmount: 65127.0,
        localMinAmount: 1.0,
        localMaxAmount: 500.0,
        country: {
            isoName: 'GH',
            name: 'Ghana',
        },
        fx: {
            rate: 0.00767647071,
            currencyCode: 'GHS',
        },
        logoUrls: [
            'https://s3.amazonaws.com/rld-operator/b20cdb4e-c7e9-46ef-bc3e-a1ef00c9b4cb-size-1.png',
            'https://s3.amazonaws.com/rld-operator/b20cdb4e-c7e9-46ef-bc3e-a1ef00c9b4cb-size-2.png',
            'https://s3.amazonaws.com/rld-operator/b20cdb4e-c7e9-46ef-bc3e-a1ef00c9b4cb-size-3.png',
        ],
        fixedAmounts: [],
        fixedAmountsDescriptions: {},
        localFixedAmounts: [],
        localFixedAmountsDescriptions: {},
        suggestedAmounts: [
            1700, 8500, 17000, 25500, 34000, 42500, 51000, 59500,
        ],
        suggestedAmountsMap: {},
        fees: {
            international: 0.0,
            local: 0.0,
            localPercentage: 0.0,
            internationalPercentage: 0.0,
        },
        geographicalRechargePlans: [],
        promotions: [],
        status: 'ACTIVE',
    },
    {
        id: 150,
        operatorId: 150,
        name: 'MTN Ghana',
        bundle: false,
        data: false,
        pin: false,
        comboProduct: false,
        supportsLocalAmounts: true,
        supportsGeographicalRechargePlans: false,
        denominationType: 'RANGE',
        senderCurrencyCode: 'NGN',
        senderCurrencySymbol: '₦',
        destinationCurrencyCode: 'GHS',
        destinationCurrencySymbol: 'GH₵',
        commission: 6.0,
        internationalDiscount: 6.0,
        localDiscount: 0.0,
        mostPopularAmount: 25500,
        mostPopularLocalAmount: null,
        minAmount: 136.0,
        maxAmount: 65127.0,
        localMinAmount: 1.0,
        localMaxAmount: 500.0,
        country: {
            isoName: 'GH',
            name: 'Ghana',
        },
        fx: {
            rate: 0.00767647071,
            currencyCode: 'GHS',
        },
        logoUrls: [
            'https://s3.amazonaws.com/rld-operator/47fdee6a-c4a1-41c0-963e-843cae07b0c9-size-2.png',
            'https://s3.amazonaws.com/rld-operator/47fdee6a-c4a1-41c0-963e-843cae07b0c9-size-3.png',
            'https://s3.amazonaws.com/rld-operator/47fdee6a-c4a1-41c0-963e-843cae07b0c9-size-1.png',
        ],
        fixedAmounts: [],
        fixedAmountsDescriptions: {},
        localFixedAmounts: [],
        localFixedAmountsDescriptions: {},
        suggestedAmounts: [
            1700, 8500, 17000, 25500, 34000, 42500, 51000, 59500,
        ],
        suggestedAmountsMap: {},
        fees: {
            international: 0.0,
            local: 0.0,
            localPercentage: 0.0,
            internationalPercentage: 0.0,
        },
        geographicalRechargePlans: [],
        promotions: [],
        status: 'ACTIVE',
    },
    {
        id: 643,
        operatorId: 643,
        name: 'MTN Ghana Data',
        bundle: false,
        data: true,
        pin: false,
        comboProduct: false,
        supportsLocalAmounts: true,
        supportsGeographicalRechargePlans: false,
        denominationType: 'FIXED',
        senderCurrencyCode: 'NGN',
        senderCurrencySymbol: '₦',
        destinationCurrencyCode: 'GHS',
        destinationCurrencySymbol: 'GH₵',
        commission: 6.0,
        internationalDiscount: 6.0,
        localDiscount: 0.0,
        mostPopularAmount: 1309.0,
        mostPopularLocalAmount: 10.0,
        minAmount: null,
        maxAmount: null,
        localMinAmount: null,
        localMaxAmount: null,
        country: {
            isoName: 'GH',
            name: 'Ghana',
        },
        fx: {
            rate: 0.00767647071,
            currencyCode: 'GHS',
        },
        logoUrls: [
            'https://s3.amazonaws.com/rld-operator/47fdee6a-c4a1-41c0-963e-843cae07b0c9-size-2.png',
            'https://s3.amazonaws.com/rld-operator/47fdee6a-c4a1-41c0-963e-843cae07b0c9-size-3.png',
            'https://s3.amazonaws.com/rld-operator/47fdee6a-c4a1-41c0-963e-843cae07b0c9-size-1.png',
        ],
        fixedAmounts: [68.0, 136.0, 391.0, 646.0, 1309.0],
        fixedAmountsDescriptions: {
            '68.00': '24MBPlan, Validity (N/A)',
            '136.00': '400MB 5AM to 8AM Kokrokoo Validity: N/A',
            '391.00': '471MBPlan',
            '646.00': '917MB VideoPlan Validity:N/A',
            '1309.00': '971MB Plan',
        },
        localFixedAmounts: [0.5, 1.09, 3.0, 5.0, 10.0],
        localFixedAmountsDescriptions: {
            '0.50': '24MBPlan, Validity (N/A)',
            '1.09': '400MB 5AM to 8AM Kokrokoo Validity: N/A',
            '3.00': '471MBPlan',
            '5.00': '917MB VideoPlan Validity:N/A',
            '10.00': '971MB Plan',
        },
        suggestedAmounts: [],
        suggestedAmountsMap: {},
        fees: {
            international: 0.0,
            local: 0.0,
            localPercentage: 0.0,
            internationalPercentage: 0.0,
        },
        geographicalRechargePlans: [],
        promotions: [],
        status: 'ACTIVE',
    },
    {
        id: 155,
        operatorId: 155,
        name: 'Telecel Ghana',
        bundle: false,
        data: false,
        pin: false,
        comboProduct: false,
        supportsLocalAmounts: true,
        supportsGeographicalRechargePlans: false,
        denominationType: 'RANGE',
        senderCurrencyCode: 'NGN',
        senderCurrencySymbol: '₦',
        destinationCurrencyCode: 'GHS',
        destinationCurrencySymbol: 'GH₵',
        commission: 5.0,
        internationalDiscount: 5.0,
        localDiscount: 0.0,
        mostPopularAmount: 8500,
        mostPopularLocalAmount: null,
        minAmount: 136.0,
        maxAmount: 13022.0,
        localMinAmount: 1.0,
        localMaxAmount: 100.0,
        country: {
            isoName: 'GH',
            name: 'Ghana',
        },
        fx: {
            rate: 0.00767647071,
            currencyCode: 'GHS',
        },
        logoUrls: [
            'https://s3.amazonaws.com/rld-operator/9d8ea314-790c-4ba8-8220-8277fc6ead3c-size-3.png',
            'https://s3.amazonaws.com/rld-operator/9d8ea314-790c-4ba8-8220-8277fc6ead3c-size-2.png',
            'https://s3.amazonaws.com/rld-operator/9d8ea314-790c-4ba8-8220-8277fc6ead3c-size-1.png',
        ],
        fixedAmounts: [],
        fixedAmountsDescriptions: {},
        localFixedAmounts: [],
        localFixedAmountsDescriptions: {},
        suggestedAmounts: [1700, 8500],
        suggestedAmountsMap: {},
        fees: {
            international: 0.0,
            local: 0.0,
            localPercentage: 0.0,
            internationalPercentage: 0.0,
        },
        geographicalRechargePlans: [],
        promotions: [],
        status: 'ACTIVE',
    },
    {
        id: 770,
        operatorId: 770,
        name: 'Telecel Ghana Data',
        bundle: false,
        data: true,
        pin: false,
        comboProduct: false,
        supportsLocalAmounts: true,
        supportsGeographicalRechargePlans: false,
        denominationType: 'FIXED',
        senderCurrencyCode: 'NGN',
        senderCurrencySymbol: '₦',
        destinationCurrencyCode: 'GHS',
        destinationCurrencySymbol: 'GH₵',
        commission: 5.0,
        internationalDiscount: 5.0,
        localDiscount: 0.0,
        mostPopularAmount: 52105.0,
        mostPopularLocalAmount: 400.0,
        minAmount: null,
        maxAmount: null,
        localMinAmount: null,
        localMaxAmount: null,
        country: {
            isoName: 'GH',
            name: 'Ghana',
        },
        fx: {
            rate: 0.00767647071,
            currencyCode: 'GHS',
        },
        logoUrls: [
            'https://s3.amazonaws.com/rld-operator/9d8ea314-790c-4ba8-8220-8277fc6ead3c-size-3.png',
            'https://s3.amazonaws.com/rld-operator/9d8ea314-790c-4ba8-8220-8277fc6ead3c-size-2.png',
            'https://s3.amazonaws.com/rld-operator/9d8ea314-790c-4ba8-8220-8277fc6ead3c-size-1.png',
        ],
        fixedAmounts: [
            68.0, 136.0, 255.0, 391.0, 646.0, 1309.0, 1955.0, 2601.0, 5661.0,
            6511.0, 13022.0, 26061.0, 39083.0, 52105.0,
        ],
        fixedAmountsDescriptions: {
            '68.00': '25MB Starter Daily',
            '136.00': '55MB Browser Daily',
            '255.00': '130MB Chat Daily',
            '391.00': '500Mb Browser Max Daily Validity: 1 Day',
            '646.00': '900MB Browser Lite Daily. Validity 3 days',
            '1309.00': '1.2GB Data . No expiration',
            '1955.00': '2.5GB Daily. Validity: 4 Days',
            '2601.00': '3GB Streamer Max Weekly',
            '5661.00': '5GB Weekly. Validity 15 Days.',
            '6511.00': '5.5GB Data. No expiration',
            '13022.00': '12GB Data. No expiration',
            '26061.00': '45GB Jumbo Streamer Validity:30Days',
            '39083.00': '130GB Monthly Jumbo Max. Validity 30 days',
            '52105.00': '230GB Jumbo Optimus Monthly. Validity 30 days',
        },
        localFixedAmounts: [
            0.5, 1.0, 2.0, 3.0, 5.0, 10.0, 15.0, 20.0, 43.5, 50.0, 100.0, 200.0,
            300.0, 400.0,
        ],
        localFixedAmountsDescriptions: {
            '0.50': '25MB Starter Daily',
            '1.00': '55MB Browser Daily',
            '2.00': '130MB Chat Daily',
            '3.00': '500Mb Browser Max Daily Validity: 1 Day',
            '5.00': '900MB Browser Lite Daily. Validity 3 days',
            '10.00': '1.2GB Data . No expiration',
            '15.00': '2.5GB Daily. Validity: 4 Days',
            '20.00': '3GB Streamer Max Weekly',
            '43.50': '5GB Weekly. Validity 15 Days.',
            '50.00': '5.5GB Data. No expiration',
            '100.00': '12GB Data. No expiration',
            '200.00': '45GB Jumbo Streamer Validity:30Days',
            '300.00': '130GB Monthly Jumbo Max. Validity 30 days',
            '400.00': '230GB Jumbo Optimus Monthly. Validity 30 days',
        },
        suggestedAmounts: [],
        suggestedAmountsMap: {},
        fees: {
            international: 0.0,
            local: 0.0,
            localPercentage: 0.0,
            internationalPercentage: 0.0,
        },
        geographicalRechargePlans: [],
        promotions: [],
        status: 'ACTIVE',
    },
];
