export const MW = [
    {
        id: 282,
        operatorId: 282,
        name: 'Airtel Malawi',
        bundle: false,
        data: false,
        pin: false,
        comboProduct: false,
        supportsLocalAmounts: true,
        supportsGeographicalRechargePlans: false,
        denominationType: 'RANGE',
        senderCurrencyCode: 'NGN',
        senderCurrencySymbol: '₦',
        destinationCurrencyCode: 'MWK',
        destinationCurrencySymbol: 'MWK',
        commission: 4.0,
        internationalDiscount: 4.0,
        localDiscount: 0.0,
        mostPopularAmount: 25500,
        mostPopularLocalAmount: null,
        minAmount: 85.0,
        maxAmount: 59500.0,
        localMinAmount: 100.0,
        localMaxAmount: 73500.0,
        country: {
            isoName: 'MW',
            name: 'Malawi',
        },
        fx: {
            rate: 1.23529411765,
            currencyCode: 'MWK',
        },
        logoUrls: [
            'https://s3.amazonaws.com/rld-operator/97f895a3-85ee-4486-8052-f8de5c167694-size-2.png',
            'https://s3.amazonaws.com/rld-operator/97f895a3-85ee-4486-8052-f8de5c167694-size-1.png',
            'https://s3.amazonaws.com/rld-operator/97f895a3-85ee-4486-8052-f8de5c167694-size-3.png',
        ],
        fixedAmounts: [],
        fixedAmountsDescriptions: {},
        localFixedAmounts: [],
        localFixedAmountsDescriptions: {},
        suggestedAmounts: [
            1700, 8500, 17000, 25500, 34000, 42500, 51000, 59500,
        ],
        suggestedAmountsMap: {},
        fees: {
            international: 0.0,
            local: 0.0,
            localPercentage: 0.0,
            internationalPercentage: 0.0,
        },
        geographicalRechargePlans: [],
        promotions: [],
        status: 'ACTIVE',
    },
    {
        id: 649,
        operatorId: 649,
        name: 'TNM Malawi',
        bundle: false,
        data: false,
        pin: false,
        comboProduct: false,
        supportsLocalAmounts: true,
        supportsGeographicalRechargePlans: false,
        denominationType: 'RANGE',
        senderCurrencyCode: 'NGN',
        senderCurrencySymbol: '₦',
        destinationCurrencyCode: 'MWK',
        destinationCurrencySymbol: 'MWK',
        commission: 4.0,
        internationalDiscount: 4.0,
        localDiscount: 0.0,
        mostPopularAmount: 17000,
        mostPopularLocalAmount: null,
        minAmount: 34.0,
        maxAmount: 24293.0,
        localMinAmount: 50.0,
        localMaxAmount: 30000.0,
        country: {
            isoName: 'MW',
            name: 'Malawi',
        },
        fx: {
            rate: 1.23529411765,
            currencyCode: 'MWK',
        },
        logoUrls: [
            'https://s3.amazonaws.com/rld-operator/9ed35235-c2ba-4c25-af4d-e3e5b484eab9-size-1.png',
            'https://s3.amazonaws.com/rld-operator/9ed35235-c2ba-4c25-af4d-e3e5b484eab9-size-2.png',
            'https://s3.amazonaws.com/rld-operator/9ed35235-c2ba-4c25-af4d-e3e5b484eab9-size-3.png',
        ],
        fixedAmounts: [],
        fixedAmountsDescriptions: {},
        localFixedAmounts: [],
        localFixedAmountsDescriptions: {},
        suggestedAmounts: [1700, 8500, 17000],
        suggestedAmountsMap: {},
        fees: {
            international: 0.0,
            local: 0.0,
            localPercentage: 0.0,
            internationalPercentage: 0.0,
        },
        geographicalRechargePlans: [],
        promotions: [],
        status: 'ACTIVE',
    },
];
