export const Assets = {
  chain: {
    base: "chain/base.png",
    celo: "chain/celo.png",
    optimism: "chain/optimism.png",
    ethereum: "chain/ethereum.png",
    bitcoin: "chain/bitcoin.png",
  },
  flags: {
    Cameroon: "flags/Cameroon.jpg",
    Europe: "flags/Europe.png",
    Ghana: "flags/Ghana.png",
    Kenya: "flags/Kenya.png",
    NGN: "flags/NGN.png",
    Rwanda: "flags/Rwanda.png",
    SouthAfrica: "flags/SouthAfrica.png",
    UK: "flags/UK.png",
    US: "flags/US.png",
    gh: "flags/gh.png",
    ke: "flags/ke.png",
    mw: "flags/mw.png",
    ng: "flags/ng.png",
    rw: "flags/rw.png",
    tz: "flags/tz.png",
    ug: "flags/ug.png",
    za: "flags/za.png",
  },
  socials: {
    Facebook: "socials/Facebook.png",
    Instagram: "socials/Instagram.png",
    Telegram: "socials/Telegram.webp",
    Twitter: "socials/Twitter.avif",
    Whatsapp: "socials/Whatsapp.png",
    Youtube: "socials/Youtube.png",
    LinkedIn: "socials/LinkedIn.png",
  },
  tokens: {
    cZAR: "tokens/cZAR.png",
    cCAD: "tokens/cCAD.png",
    cAUD: "tokens/cAUD.png",
    cCHF: "tokens/cCHF.png",
    cJPY: "tokens/cJPY.png",
    cNGN: "tokens/cNGN.png",
    cGBP: "tokens/cGBP.png",
    //
    USDT: "tokens/USDT.png",
    USDC: "tokens/USDC.png",
    PUSO: "tokens/PUSO.png",
    eXOF: "tokens/eXOF.png",
    cUSD: "tokens/cUSD.png",
    cREAL: "tokens/cREAL.png",
    cKES: "tokens/cKES.png",
    cGHS: "tokens/cGHS.png",
    cEUR: "tokens/cEUR.png",
    CELO: "tokens/CELO.png",
    cCOP: "tokens/cCOP.png",
    axIUSDC: "tokens/axIUSDC.png",
    axIEUROC: "tokens/axIEUROC.png",
    bitcoin: "tokens/bitcoin.png",
    optimism: "tokens/optimism.png",
    ethereum: "tokens/ethereum.png",
  },
};
