export const localOperators = [
  {
    id: 341,
    operatorId: 341,
    name: 'MTN Nigeria',
    bundle: false,
    data: false,
    pin: false,
    comboProduct: false,
    supportsLocalAmounts: true,
    supportsGeographicalRechargePlans: false,
    denominationType: 'RANGE',
    senderCurrencyCode: 'NGN',
    senderCurrencySymbol: '₦',
    destinationCurrencyCode: 'NGN',
    destinationCurrencySymbol: '₦',
    commission: 3.0,
    internationalDiscount: 3.0,
    localDiscount: 0.0,
    mostPopularAmount: null,
    mostPopularLocalAmount: null,
    minAmount: 50.0,
    maxAmount: 200000,
    localMinAmount: null,
    localMaxAmount: null,
    country: {
      isoName: 'NG',
      name: 'Nigeria',
    },
    fx: {
      rate: 1,
      currencyCode: 'NGN',
    },
    logoUrls: [
      'https://s3.amazonaws.com/rld-operator/cc553249-f52a-4b86-9dc4-68dda963b1b3-size-3.png',
      'https://s3.amazonaws.com/rld-operator/cc553249-f52a-4b86-9dc4-68dda963b1b3-size-1.png',
      'https://s3.amazonaws.com/rld-operator/cc553249-f52a-4b86-9dc4-68dda963b1b3-size-2.png',
    ],
    fixedAmounts: [],
    fixedAmountsDescriptions: {},
    localFixedAmounts: [],
    localFixedAmountsDescriptions: {},
    suggestedAmounts: [],
    suggestedAmountsMap: {},
    fees: {
      international: 0.0,
      local: 0.0,
      localPercentage: 0.0,
      internationalPercentage: 0.0,
    },
    geographicalRechargePlans: [],
    promotions: [],
    status: 'ACTIVE',
  },
  {
    id: 344,
    operatorId: 344,
    name: 'Glo Nigeria',
    bundle: false,
    data: false,
    pin: false,
    comboProduct: false,
    supportsLocalAmounts: true,
    supportsGeographicalRechargePlans: false,
    denominationType: 'RANGE',
    senderCurrencyCode: 'NGN',
    senderCurrencySymbol: '₦',
    destinationCurrencyCode: 'NGN',
    destinationCurrencySymbol: '₦',
    commission: 5.0,
    internationalDiscount: 5.0,
    localDiscount: 0.0,
    mostPopularAmount: null,
    mostPopularLocalAmount: null,
    minAmount: 50.0,
    maxAmount: 50000,
    localMinAmount: null,
    localMaxAmount: null,
    country: {
      isoName: 'NG',
      name: 'Nigeria',
    },
    fx: {
      rate: 1,
      currencyCode: 'NGN',
    },
    logoUrls: [
      'https://s3.amazonaws.com/rld-operator/18416726-e966-4ed0-b352-f02e9e9ff9db-size-1.png',
      'https://s3.amazonaws.com/rld-operator/18416726-e966-4ed0-b352-f02e9e9ff9db-size-2.png',
      'https://s3.amazonaws.com/rld-operator/18416726-e966-4ed0-b352-f02e9e9ff9db-size-3.png',
    ],
    fixedAmounts: [],
    fixedAmountsDescriptions: {},
    localFixedAmounts: [],
    localFixedAmountsDescriptions: {},
    suggestedAmounts: [],
    suggestedAmountsMap: {},
    fees: {
      international: 0.0,
      local: 0.0,
      localPercentage: 0.0,
      internationalPercentage: 0.0,
    },
    geographicalRechargePlans: [],
    promotions: [],
    status: 'ACTIVE',
  },
  {
    id: 342,
    operatorId: 342,
    name: 'Airtel Nigeria',
    bundle: false,
    data: false,
    pin: false,
    comboProduct: false,
    supportsLocalAmounts: true,
    supportsGeographicalRechargePlans: false,
    denominationType: 'RANGE',
    senderCurrencyCode: 'NGN',
    senderCurrencySymbol: '₦',
    destinationCurrencyCode: 'NGN',
    destinationCurrencySymbol: '₦',
    commission: 4.0,
    internationalDiscount: 4.0,
    localDiscount: 0.0,
    mostPopularAmount: null,
    mostPopularLocalAmount: null,
    minAmount: 50.0,
    maxAmount: 199999,
    localMinAmount: null,
    localMaxAmount: null,
    country: {
      isoName: 'NG',
      name: 'Nigeria',
    },
  },
  {
    id: 340,
    operatorId: 340,
    name: '9Mobile (Etisalat) Nigeria',
    bundle: false,
    data: false,
    pin: false,
    comboProduct: false,
    supportsLocalAmounts: true,
    supportsGeographicalRechargePlans: false,
    denominationType: 'RANGE',
    senderCurrencyCode: 'NGN',
    senderCurrencySymbol: '₦',
    destinationCurrencyCode: 'NGN',
    destinationCurrencySymbol: '₦',
    commission: 6.0,
    internationalDiscount: 6.0,
    localDiscount: 0.0,
    mostPopularAmount: null,
    mostPopularLocalAmount: null,
    minAmount: 50.0,
    maxAmount: 50000,
    localMinAmount: null,
    localMaxAmount: null,
    country: {
      isoName: 'NG',
      name: 'Nigeria',
    },
    fx: {
      rate: 1,
      currencyCode: 'NGN',
    },
    logoUrls: [
      'https://s3.amazonaws.com/rld-operator/a6c9c490-39fa-47c0-a63a-b4a4d1d4dbe5-size-3.png',
      'https://s3.amazonaws.com/rld-operator/a6c9c490-39fa-47c0-a63a-b4a4d1d4dbe5-size-2.png',
      'https://s3.amazonaws.com/rld-operator/a6c9c490-39fa-47c0-a63a-b4a4d1d4dbe5-size-1.png',
    ],
    fixedAmounts: [],
    fixedAmountsDescriptions: {},
    localFixedAmounts: [],
    localFixedAmountsDescriptions: {},
    suggestedAmounts: [],
    suggestedAmountsMap: {},
    fees: {
      international: 0.0,
      local: 0.0,
      localPercentage: 0.0,
      internationalPercentage: 0.0,
    },
    geographicalRechargePlans: [],
    promotions: [],
    status: 'ACTIVE',
  },
];
